"""create_initial_tables

Revision ID: 202403150000
Revises: 
Create Date: 2024-03-15 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func # For server_default func.now()


# revision identifiers, used by Alembic.
revision: str = '202403150000' # Example revision ID, should be unique
down_revision: Union[str, None] = None # This is the first migration
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=True), # Default to True (1 for boolean in SQL)
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # If UserConfiguration table was defined, it would be created here too.
    # Example for UserConfiguration (if it existed in models.py and was one-to-one with User):
    # op.create_table('user_configurations',
    # sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id'), nullable=False, unique=True), # Unique for one-to-one
    # sa.Column('some_setting', sa.String(length=100), nullable=True),
    # sa.Column('created_at', sa.DateTime(timezone=True), server_default=func.now(), nullable=True),
    # sa.Column('updated_at', sa.DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_user_configurations_id'), 'user_configurations', ['id'], unique=False)
    # op.create_index(op.f('ix_user_configurations_user_id'), 'user_configurations', ['user_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_user_configurations_user_id'), table_name='user_configurations') # if UserConfiguration table existed
    # op.drop_index(op.f('ix_user_configurations_id'), table_name='user_configurations')       # if UserConfiguration table existed
    # op.drop_table('user_configurations')                                                  # if UserConfiguration table existed
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
